version: "3"
services:

  oj-redis:
    image: redis:4.0-alpine
    container_name: oj-redis
    restart: always
    volumes:
      - ./data/redis:/data

  oj-postgres:
    image: postgres:10-alpine
    container_name: oj-postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge

  oj-judge:
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    container_name: oj-judge
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS
      # - judger_debug=1

  oj-backend:
    image: crpi-al80mno0m25s5teh.cn-shanghai.personal.cr.aliyuncs.com/python_edu/oj-backend:1.6.2
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - oj-judge
    volumes:
      - ./data/backend:/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=CHANGE_THIS
      # - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
    ports:
      - "0.0.0.0:80:8000"
      - "0.0.0.0:443:1443"

  java-edu:
      image: crpi-al80mno0m25s5teh.cn-shanghai.personal.cr.aliyuncs.com/java_edu/java_edu:3.9.1
      container_name: java-edu
      privileged: true
#     network_mode: host
      restart: always
      depends_on:
        - oj-postgres
      environment:
        - POSTGRES_DB=onlinejudge
        - POSTGRES_USER=onlinejudge
        - POSTGRES_PASSWORD=onlinejudge
        - DB_HOST=oj-postgres
      command:
          /bin/bash -c "java -Duser.timezone=Asia/Shanghai -jar -Dspring.profiles.active=prod /app/xzs-3.9.1.jar"
      ports:
          - "8888:8888"
      volumes:
          - "./release:/usr/local/xzs/release/"
          - "./log:/usr/log/xzs/"
