logging:
  path: ./log/aikes/

spring:
  datasource:
    url: jdbc:postgresql://oj-postgres:5432/onlinejudge
    username: onlinejudge
    password: onlinejudge
    driver-class-name: org.postgresql.Driver

# logging:
#   path: ./log/aikes/
#
# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/onlinejudge
#     username: postgres
#     password: 123456
#     driver-class-name: org.postgresql.Driver

